# services/database_service.py
# Database persistence layer for DocMind AI.
#
# This service handles all database writes for document uploads. It abstracts
# SQLAlchemy operations into clean, single-responsibility functions that route
# handlers can call without knowing ORM internals.
#
# Key responsibility:
#   save_document_with_chunks() — atomically persists one Document and all
#   its related Chunks in a SINGLE transaction, guaranteeing consistency.
#   If anything fails, the entire operation is rolled back — no partial writes.

# Session is the SQLAlchemy session type, typically injected via Depends(get_db).
from sqlalchemy.orm import Session

# Document and Chunk are the ORM models. We construct instances and hand them
# to SQLAlchemy, which generates the INSERT statements and manages the transaction.
from app.models.document import Document
from app.models.chunk import Chunk


def save_document_with_chunks(
    db: Session,
    filename: str,
    chunks: list[str],
    embeddings: list[list[float]],
) -> Document:
    """
    Create a Document row and all its associated Chunk rows in one transaction.

    Uses a single transaction with flush() + commit() pattern:
      - flush() sends the Document INSERT to the database within the open
        transaction so PostgreSQL generates its primary key ID, while keeping
        the transaction open so chunks can reference that ID in the same unit
        of work.
      - commit() is called exactly once, after all objects are ready.
      - On any exception, rollback() undoes all changes atomically — no
        partial writes, no orphaned document rows.

    Args:
        db:         An active SQLAlchemy session (injected by get_db()).
        filename:   The original PDF filename (e.g. "annual_report.pdf").
        chunks:     List of text chunk strings produced by chunk_service.
        embeddings: List of 384-dim embedding vectors, one per chunk.
                    Must have the same length as chunks.

    Returns:
        The created Document instance, with id and uploaded_at populated
        from the database after the final commit.

    Raises:
        ValueError:      If len(chunks) != len(embeddings).
        IntegrityError:  If a database constraint is violated.
        Exception:       Any other unexpected error — rolled back and re-raised.
    """

    # ---------------------------------------------------------------------------
    # Validation
    # ---------------------------------------------------------------------------
    # Defensive check: chunks and embeddings must be parallel arrays.
    # A mismatch means the upstream pipeline produced inconsistent data.
    # Raised before touching the database so no rollback is needed here.
    if len(chunks) != len(embeddings):
        raise ValueError(
            f"Mismatch: {len(chunks)} chunks vs {len(embeddings)} embeddings. "
            "Both lists must have the same length."
        )

    try:
        # -----------------------------------------------------------------------
        # Step 1: Add the Document and flush to obtain its generated ID
        # -----------------------------------------------------------------------
        # Construct a Document ORM instance in memory.
        # id and uploaded_at will be generated by PostgreSQL on flush.
        document = Document(filename=filename)

        # Mark the document as pending in this session's identity map.
        # No SQL is sent to the database yet.
        db.add(document)

        # flush() sends the INSERT INTO documents ... to the database within
        # the CURRENT OPEN TRANSACTION. PostgreSQL generates id (SERIAL) and
        # uploaded_at (NOW()), making them available to Python immediately.
        # Unlike commit(), flush() does NOT close the transaction — we can
        # still add chunk rows to the same unit of work and roll everything
        # back together if something goes wrong.
        db.flush()

        # After flush(), document.id is populated with the database-generated
        # integer. We can now use it as the foreign key in Chunk rows.

        # -----------------------------------------------------------------------
        # Step 2: Build all Chunk objects and add them to the session
        # -----------------------------------------------------------------------
        # Accumulate Chunk instances in memory before bulk-adding.
        chunk_objects = []

        # zip() pairs each chunk text with its corresponding embedding vector.
        # enumerate() provides the 0-based index that becomes chunk_index.
        # This preserves the original sequence so chunks can be reassembled.
        for index, (text, emb) in enumerate(zip(chunks, embeddings)):

            # Construct a Chunk ORM instance with all required fields.
            # document_id references the ID we obtained from the flush above.
            chunk = Chunk(
                document_id=document.id,  # FK — now a real integer, not None
                chunk_index=index,        # 0, 1, 2, ... preserves order
                chunk_text=text,          # The actual text slice
                embedding=emb,            # 384-float vector as list[float]
            )

            chunk_objects.append(chunk)

        # Mark all chunk instances as pending in one call.
        # add_all() is more efficient than calling add() in a loop.
        db.add_all(chunk_objects)

        # -----------------------------------------------------------------------
        # Step 3: Commit the single transaction
        # -----------------------------------------------------------------------
        # This is the only commit() in the function.
        # PostgreSQL writes the Document row and all Chunk rows atomically:
        # either all rows are committed or none are.
        # If this fails (e.g. constraint violation, network error), the except
        # block rolls back everything — no orphaned document, no partial chunks.
        db.commit()

        # -----------------------------------------------------------------------
        # Step 4: Refresh the Document after the final commit
        # -----------------------------------------------------------------------
        # refresh() re-reads the document row from the database, populating
        # id, uploaded_at, and any other server-generated values with their
        # final committed state. This is done after commit() so the object
        # reflects fully durable, persisted data.
        db.refresh(document)

        # Return the fully populated Document instance to the caller.
        return document

    except Exception:
        # -----------------------------------------------------------------------
        # Rollback on any failure
        # -----------------------------------------------------------------------
        # db.rollback() undoes the entire transaction atomically.
        # Because we used flush() instead of commit() for the Document insert,
        # both the Document row and all Chunk rows are rolled back together —
        # no partial writes, no orphaned rows, no inconsistent database state.
        # raise (bare) re-raises the original exception unchanged so the caller
        # sees the real error type and message, not a wrapped version of it.
        db.rollback()
        raise


def get_latest_document_chunks(
    db: Session,
) -> tuple[list[str], list[list[float]]]:
    """
    Retrieve the chunks and embeddings of the most recently uploaded document.

    Queries the documents table for the latest row by uploaded_at, then loads
    all associated chunk rows ordered by position so they can be used directly
    for semantic search without re-processing the document.

    Args:
        db: An active SQLAlchemy session (injected by get_db()).

    Returns:
        A tuple (chunk_texts, chunk_embeddings) where:
          chunk_texts      — list[str]            ordered by chunk_index asc
          chunk_embeddings — list[list[float]]    ordered by chunk_index asc
        Returns ([], []) if no document exists in the database.
    """

    # ---------------------------------------------------------------------------
    # Step 1: Find the most recently uploaded Document
    # ---------------------------------------------------------------------------
    # order_by(Document.uploaded_at.desc()) sorts rows newest-first.
    # .first() fetches only the top row (LIMIT 1) and returns None if the
    # table is empty — no exception is raised on an empty table.
    document = (
        db.query(Document)
        .order_by(Document.uploaded_at.desc())
        .first()
    )

    # If no document row exists yet, there is nothing to retrieve.
    # Return two empty lists so callers can check `if not chunks` cleanly
    # without handling None or catching an exception.
    if document is None:
        return [], []

    # ---------------------------------------------------------------------------
    # Step 2: Load all Chunk rows for this Document, ordered by position
    # ---------------------------------------------------------------------------
    # filter(Chunk.document_id == document.id) generates WHERE document_id = <id>.
    # order_by(Chunk.chunk_index.asc()) restores the original chunk sequence
    # (0, 1, 2, ...) — without this, PostgreSQL may return rows in any order.
    # .all() fetches every matching row as a list of Chunk ORM instances.
    chunk_rows = (
        db.query(Chunk)
        .filter(Chunk.document_id == document.id)
        .order_by(Chunk.chunk_index.asc())
        .all()
    )

    # ---------------------------------------------------------------------------
    # Step 3: Extract the two parallel lists from the ORM instances
    # ---------------------------------------------------------------------------
    # List comprehension over chunk_rows preserves the ORDER BY ordering.
    # chunk_text is a plain Python str column value.
    chunk_texts = [row.chunk_text for row in chunk_rows]

    # row.embedding is stored in PostgreSQL as a vector(384) column.
    # The pgvector SQLAlchemy adapter reads it back as a Python list[float],
    # so no extra conversion is needed here.
    chunk_embeddings = [row.embedding for row in chunk_rows]

    # Return both lists as a tuple. The caller can unpack them directly:
    #   chunks, embeddings = get_latest_document_chunks(db)
    return chunk_texts, chunk_embeddings
